### PR TITLE
Fix token verification where original token was encoded with whitespace

### LINKED ISSUE #109: Signature verification does not work when the token was encoded with whitespace
In [RFC 7519 Section 7.1](https://tools.ietf.org/html/rfc7519#section-7.1) it mentions 

> Create a JWT Claims Set containing the desired claims.  Note that
       whitespace is explicitly allowed in the representation and no
       canonicalization need be performed before encoding.

Additionally, in [RFC 7515 Section 3](https://tools.ietf.org/html/rfc7515#section-3) it mentions

> JWS represents digitally signed or MACed content using JSON data
   structures and base64url encoding.  These JSON data structures MAY
   contain whitespace and/or line breaks before or after any JSON values
   or structural characters, in accordance with Section 2 of RFC 7159
   [RFC7159].

However, when generating a token with whitespace or line breaks in the JSON, the token does not pass the verification. For example, **Example 1** below fails verification, whereas **Example 2** passes verification.

###### Example 1
```PHP
$header = '{
    "alg": "RS256"
}';

$payload = '{
    "a": "b"
}';

$encoder = new Base64UrlSafeEncoder();
$token = sprintf('%s.%s', $encoder->encode($header), $encoder->encode($payload));
$signer = new RS256();

$privateKey = openssl_pkey_get_private('path/to/private/key');
$signature = $encoder->encode($signer->sign($token, $privateKey));
$jwsToken = sprintf('%s.%s', $token, $signature);

$jws = JWS::load($jwsToken);
$publicKey = openssl_pkey_get_public('path/to/public/key');

$jws->verify($publicKey); // Returns false
```

###### Example 2
```PHP
$header = '{"alg":"RS256"}';
$payload = '{"a":"b"}';

$encoder = new Base64UrlSafeEncoder();
$token = sprintf('%s.%s', $encoder->encode($header), $encoder->encode($payload));
$signer = new RS256();

$privateKey = openssl_pkey_get_private('path/to/private/key');
$signature = $encoder->encode($signer->sign($token, $privateKey));
$jwsToken = sprintf('%s.%s', $token, $signature);

$jws = JWS::load($jwsToken);
$publicKey = openssl_pkey_get_public('path/to/public/key');

$jws->verify($publicKey); // Returns true
```

It looks like the verify method takes the decoded header and payload arrays, JSON encodes them, then base64 encodes them. It then uses these values to generate the input that will be checked against the signature. However, since it decodes the token, then re-encodes it, the formatting is lost and the resulting signature is different. 

Maybe it should take the original header and payload and use that to check against the signature, so that any formatting changes don't impact the verification step.

### PR DESCRIPTION
**Pull request by jshayes**
Fixes #109

Currently, the original token string it not stored anywhere. This token is decoded and those decoded values are stored. When you try to verify the signature, the header and payload are then re-encoded and checked against the signature. The issue with this is that the original formatting is lost when re-encoding the token. This change uses the original token, if present, to verify the signature against.

### CODE REVIEW

File: src/Namshi/JOSE/JWS.php [hunk 1]
```diff
@@ -157,12 +159,43 @@ public function verify($key, $algo = null)
...
+     */
+    private function getSigninInput()
+    {
+        $parts = explode('.', $this->originalToken);
+
+        if (count($parts) >= 2) {
+            return sprintf('%s.%s', $parts[0], $parts[1]);
+        }
+
+        return $this->generateSigninInput();
```
Comment (odino) [inline src/Namshi/JOSE/JWS.php]: hey @jshayes thanks for this! Any reason we would need to fallback to the original `generateSigninInput`?

Comment (odino) [inline src/Namshi/JOSE/JWS.php]: how can we create the token without going through the `load` method? Sorry, just trying to remember :)

Comment (jshayes) [inline src/Namshi/JOSE/JWS.php]: All the methods to build the state of the token are publicly exposed, so you can call them to create a token manually. For example, you can create a new instance of `JWS` and then call `setHeader` and `setPayload` to build the token.
